# Generated by Django 5.2.7 on 2025-10-20 01:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('DEPORTE', 'Deporte'), ('CULTURA', 'Cultura'), ('EVENTO', 'Evento'), ('BIENESTAR', 'Bienestar'), ('OTRO', 'Otro')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('available_spots', models.PositiveIntegerField()),
                ('instructor', models.CharField(blank=True, max_length=120)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='active', max_length=16)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['start'], name='actividades_start_a6150a_idx'), models.Index(fields=['category'], name='actividades_categor_3aee6d_idx'), models.Index(fields=['status'], name='actividades_status_09228c_idx')],
            },
        ),
    ]
