# actividades/migrations/0002_alter_activity_tags.py
# Generated by Django 5.2.7 on 2025-10-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actividades", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE actividades_activity "
                        "ALTER COLUMN tags TYPE jsonb "
                        "USING to_jsonb(tags);"
                    ),
                    reverse_sql=(
                        "ALTER TABLE actividades_activity "
                        "ALTER COLUMN tags TYPE character varying(24)[] "
                        "USING CASE "
                        "WHEN tags IS NULL THEN NULL "
                        "WHEN jsonb_typeof(tags) <> 'array' THEN NULL "
                        "ELSE ARRAY("
                        "SELECT value FROM jsonb_array_elements_text(tags) AS arr(value)"
                        ") END::character varying(24)[];"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='activity',
                    name='tags',
                    field=models.JSONField(blank=True, default=list, null=True),
                ),
            ],
        ),
    ]
