# Generated by Django 5.2.7 on 2025-10-27 23:53

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_userprofile'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE actividades_userprofile "
                        "ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT NOW();"
                    ),
                    reverse_sql=(
                        "ALTER TABLE actividades_userprofile "
                        "DROP COLUMN IF EXISTS created_at;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE actividades_userprofile "
                        "ADD COLUMN IF NOT EXISTS role varchar(20) NOT NULL DEFAULT 'BENEFICIARY';"
                    ),
                    reverse_sql=(
                        "ALTER TABLE actividades_userprofile "
                        "DROP COLUMN IF EXISTS role;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE actividades_userprofile "
                        "ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT NOW();"
                    ),
                    reverse_sql=(
                        "ALTER TABLE actividades_userprofile "
                        "DROP COLUMN IF EXISTS updated_at;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='created_at',
                    field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                migrations.AddField(
                    model_name='userprofile',
                    name='role',
                    field=models.CharField(choices=[('BENEFICIARY', 'Beneficiario/Estudiante'), ('ADMIN', 'Administrador')], default='BENEFICIARY', max_length=20),
                ),
                migrations.AddField(
                    model_name='userprofile',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='program',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
