# Generated by Django 5.2.7 on 2025-10-28 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_userprofile_created_at_userprofile_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sport', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=16)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='planned', max_length=16)),
                ('max_teams', models.PositiveIntegerField(default=0)),
                ('current_teams', models.PositiveIntegerField(default=0)),
                ('fixtures', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['start'], name='actividades_start_73eae8_idx'), models.Index(fields=['status'], name='actividades_status_b8edc7_idx'), models.Index(fields=['visibility'], name='actividades_visibil_1cc34f_idx')],
            },
        ),
    ]
