# Generated by Django 5.2.7 on 2025-10-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tournament',
            name='inscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='inscription_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
