# Generated by Django 5.2.7 on 2025-11-09 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_tournament_format_tournament_inscription_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='assigned_professor',
            field=models.ForeignKey(blank=True, help_text='Profesor responsable (usuario con rol PROFESOR)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('BENEFICIARY', 'Beneficiario/Estudiante'), ('ADMIN', 'Administrador'), ('PROFESSOR', 'Profesor')], default='BENEFICIARY', max_length=20),
        ),
    ]
