# Generated by Django 4.2.25 on 2025-11-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_project_userprofile_created_at_userprofile_role_and_more'),
        ('actividades', '0009_activity_checkin_fields'),
    ]

    operations = [
    ]
