# Generated by Django 5.2.7 on 2025-11-10 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _create_campaign_table_if_not_exists(apps, schema_editor):
    table_names = set(schema_editor.connection.introspection.table_names())
    if 'actividades_campaign' in table_names:
        return

    class Campaign(models.Model):
        name = models.CharField(max_length=160)
        message = models.TextField()
        channel_option = models.CharField(max_length=16, choices=[('CORREO', 'Correo'), ('PUSH', 'Push/App'), ('AMBOS', 'Ambos')], default='AMBOS')
        segment = models.CharField(max_length=32, choices=[('Todos los usuarios', 'Todos los usuarios'), ('Solo Estudiantes', 'Solo Estudiantes'), ('Solo Profesores', 'Solo Profesores'), ('Seleccionados', 'Seleccionados')], default='Todos los usuarios')
        selected_user_ids = models.JSONField(null=True, blank=True, default=list)
        schedule_at = models.DateTimeField(null=True, blank=True)
        total_recipients = models.PositiveIntegerField(default=0)
        app_sent = models.PositiveIntegerField(default=0)
        emails_sent = models.PositiveIntegerField(default=0)
        created_at = models.DateTimeField(auto_now_add=True)
        created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns_created')

        class Meta:
            app_label = 'actividades'
            db_table = 'actividades_campaign'

    schema_editor.create_model(Campaign)


def _create_notification_table_if_not_exists(apps, schema_editor):
    table_names = set(schema_editor.connection.introspection.table_names())
    if 'actividades_notification' in table_names:
        return

    class Notification(models.Model):
        title = models.CharField(max_length=200)
        body = models.TextField()
        channel = models.CharField(max_length=16, choices=[('app', 'App'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')])
        status = models.CharField(max_length=16, choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='pending')
        priority = models.CharField(max_length=16, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal')
        scheduled_for = models.DateTimeField(null=True, blank=True)
        sent_at = models.DateTimeField(null=True, blank=True)
        read_at = models.DateTimeField(null=True, blank=True)
        metadata = models.JSONField(blank=True, default=dict)
        created_at = models.DateTimeField(auto_now_add=True)
        user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.CASCADE, related_name='notifications')
        activity = models.ForeignKey('actividades.Activity', on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name='notifications')
        campaign = models.ForeignKey('actividades.Campaign', on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name='notifications')

        class Meta:
            app_label = 'actividades'
            db_table = 'actividades_notification'

    schema_editor.create_model(Notification)


def _create_deliverylog_table_if_not_exists(apps, schema_editor):
    table_names = set(schema_editor.connection.introspection.table_names())
    if 'actividades_notificationdeliverylog' in table_names:
        return

    class NotificationDeliveryLog(models.Model):
        notification = models.ForeignKey('actividades.Notification', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs')
        channel = models.CharField(max_length=16, choices=[('app', 'App'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')])
        status = models.CharField(max_length=16, choices=[('success', 'Success'), ('error', 'Error')])
        detail = models.TextField(blank=True, default='')
        created_at = models.DateTimeField(auto_now_add=True)

        class Meta:
            app_label = 'actividades'
            db_table = 'actividades_notificationdeliverylog'

    schema_editor.create_model(NotificationDeliveryLog)


def _create_preferences_table_if_not_exists(apps, schema_editor):
    table_names = set(schema_editor.connection.introspection.table_names())
    if 'actividades_notificationpreference' in table_names:
        return

    class NotificationPreference(models.Model):
        email_enabled = models.BooleanField(default=True)
        app_enabled = models.BooleanField(default=True)
        push_enabled = models.BooleanField(default=False)
        sms_enabled = models.BooleanField(default=False)
        quiet_hours_start = models.TimeField(null=True, blank=True)
        quiet_hours_end = models.TimeField(null=True, blank=True)
        updated_at = models.DateTimeField(auto_now=True)
        user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences')

        class Meta:
            app_label = 'actividades'
            db_table = 'actividades_notificationpreference'

    schema_editor.create_model(NotificationPreference)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_alter_enrollment_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_create_campaign_table_if_not_exists, reverse_code=_noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Campaign',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=160)),
                        ('message', models.TextField()),
                        ('channel_option', models.CharField(choices=[('CORREO', 'Correo'), ('PUSH', 'Push/App'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=16)),
                        ('segment', models.CharField(choices=[('Todos los usuarios', 'Todos los usuarios'), ('Solo Estudiantes', 'Solo Estudiantes'), ('Solo Profesores', 'Solo Profesores'), ('Seleccionados', 'Seleccionados')], default='Todos los usuarios', max_length=32)),
                        ('selected_user_ids', models.JSONField(blank=True, default=list, null=True)),
                        ('schedule_at', models.DateTimeField(blank=True, null=True)),
                        ('total_recipients', models.PositiveIntegerField(default=0)),
                        ('app_sent', models.PositiveIntegerField(default=0)),
                        ('emails_sent', models.PositiveIntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_create_notification_table_if_not_exists, reverse_code=_noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('body', models.TextField()),
                        ('channel', models.CharField(choices=[('app', 'App'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], max_length=16)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=16)),
                        ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=16)),
                        ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                        ('sent_at', models.DateTimeField(blank=True, null=True)),
                        ('read_at', models.DateTimeField(blank=True, null=True)),
                        ('metadata', models.JSONField(blank=True, default=dict)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='actividades.activity')),
                        ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='actividades.campaign')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_create_deliverylog_table_if_not_exists, reverse_code=_noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='NotificationDeliveryLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('channel', models.CharField(choices=[('app', 'App'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], max_length=16)),
                        ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=16)),
                        ('detail', models.TextField(blank=True, default='')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='actividades.notification')),
                    ],
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_create_preferences_table_if_not_exists, reverse_code=_noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='NotificationPreference',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('email_enabled', models.BooleanField(default=True)),
                        ('app_enabled', models.BooleanField(default=True)),
                        ('push_enabled', models.BooleanField(default=False)),
                        ('sms_enabled', models.BooleanField(default=False)),
                        ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                        ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX IF NOT EXISTS actividades_user_id_e5d57d_idx ON actividades_notification (user_id, status);'
                    ),
                    reverse_sql=(
                        'DROP INDEX IF EXISTS actividades_user_id_e5d57d_idx;'
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX IF NOT EXISTS actividades_schedul_c50324_idx ON actividades_notification (scheduled_for);'
                    ),
                    reverse_sql=(
                        'DROP INDEX IF EXISTS actividades_schedul_c50324_idx;'
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX IF NOT EXISTS actividades_activit_441b13_idx ON actividades_notification (activity_id, channel);'
                    ),
                    reverse_sql=(
                        'DROP INDEX IF EXISTS actividades_activit_441b13_idx;'
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX IF NOT EXISTS actividades_campaig_b06f53_idx ON actividades_notification (campaign_id);'
                    ),
                    reverse_sql=(
                        'DROP INDEX IF EXISTS actividades_campaig_b06f53_idx;'
                    ),
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='notification',
                    index=models.Index(fields=['user', 'status'], name='actividades_user_id_e5d57d_idx'),
                ),
                migrations.AddIndex(
                    model_name='notification',
                    index=models.Index(fields=['scheduled_for'], name='actividades_schedul_c50324_idx'),
                ),
                migrations.AddIndex(
                    model_name='notification',
                    index=models.Index(fields=['activity', 'channel'], name='actividades_activit_441b13_idx'),
                ),
                migrations.AddIndex(
                    model_name='notification',
                    index=models.Index(fields=['campaign'], name='actividades_campaig_b06f53_idx'),
                ),
            ],
        ),
    ]
